# Конфігурація тренування YOLOv8
model: yolov8n.pt
data: data.yaml

# Параметри тренування
epochs: 100
batch: 16
imgsz: 640
device: cpu
workers: 2

# Налаштування оптимізатора
optimizer: "Adam"
lr0: 0.01
momentum: 0.937
weight_decay: 0.0005

# Інтеграція W&B
wandb_project: "setuniversity-mlops-s25"
run_name: "yolo-ray-training"

# Збереження моделі
save: true